const CFG = window.DECOR_CONFIG || {};
let sb = null, session = null, products = [], customers = [], cart = [];
const money = n => `${Number(n||0).toFixed(2)} ₼`;
const esc = s => String(s ?? "").replace(/[&<>"']/g, m => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(msg, ok=true){const t=document.getElementById('toast');t.textContent=msg;t.className=`fixed bottom-5 right-5 z-50 px-4 py-3 rounded-xl text-white shadow-xl ${ok?'bg-emerald-600':'bg-rose-600'}`;setTimeout(()=>t.classList.add('hidden'),2800)}
function configured(){return CFG.SUPABASE_URL && !CFG.SUPABASE_URL.includes('PASTE_') && CFG.SUPABASE_ANON_KEY && !CFG.SUPABASE_ANON_KEY.includes('PASTE_')}
async function api(action,payload={}) {
  if(!session) throw Error("Sessiya yoxdur");
  const r=await fetch(`${CFG.SUPABASE_URL}/functions/v1/api`,{
    method:"POST",headers:{"Content-Type":"application/json","apikey":CFG.SUPABASE_ANON_KEY},
    body:JSON.stringify({action,session_token:session.token,...payload})
  });
  const j=await r.json().catch(()=>({}));
  if(!r.ok || j.error) throw Error(j.error||"Server xətası");
  return j;
}
function nav(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.getElementById(v)?.classList.add('active');document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===v));if(v==='dashboard')loadDashboard();if(v==='products')renderProductsTable();if(v==='customers')renderCustomersTable();if(v==='stock')renderStockSelect();if(v==='reports')loadSales()}
async function login(){
  if(!configured()){showLoginError("Əvvəlcə frontend/config.js faylında Supabase URL və public key yazılmalıdır.");return}
  const pin=document.getElementById('pin').value.trim(); if(!pin)return;
  try{const j=await fetch(`${CFG.SUPABASE_URL}/functions/v1/api`,{method:"POST",headers:{"Content-Type":"application/json","apikey":CFG.SUPABASE_ANON_KEY},body:JSON.stringify({action:"login",pin})});const d=await j.json();if(!j.ok||d.error)throw Error(d.error||"PIN səhvdir");session=d;localStorage.setItem("decor_session",JSON.stringify(d));startApp()}catch(e){showLoginError(e.message)}
}
function showLoginError(s){const x=document.getElementById('loginError');x.textContent=s;x.classList.remove('hidden')}
function logout(){session=null;localStorage.removeItem("decor_session");location.reload()}
async function startApp(){document.getElementById('login').classList.add('hidden');document.getElementById('app').classList.remove('hidden');document.getElementById('userBadge').textContent=`${session.user.name} · ${session.user.role}`;await loadAll();nav('dashboard')}
async function loadAll(){const j=await api("bootstrap");products=j.products||[];customers=j.customers||[];document.getElementById('serverDate').textContent=`Server vaxtı: ${j.server_time}`;renderProductResults();renderCustomersSelect();renderProductsTable();renderCustomersTable();renderStockSelect()}
function renderCustomersSelect(){const s=document.getElementById('customerSelect');s.innerHTML='<option value="">Nağd Müştəri</option>'+customers.map(c=>`<option value="${c.id}">${esc(c.name)}${c.phone?' · '+esc(c.phone):''}</option>`).join('')}
function renderProductResults(){
  const q=(document.getElementById('productSearch')?.value||'').toLowerCase().trim(), box=document.getElementById('productResults');let list=products.filter(p=>!q||`${p.code} ${p.name} ${p.barcode||''}`.toLowerCase().includes(q)).slice(0,60);
  box.innerHTML=list.map((p,i)=>`<button class="productBtn text-left border rounded-2xl p-4 hover:border-blue-500 hover:bg-blue-50 ${i===0?'ring-2 ring-blue-100':''}" data-id="${p.id}"><div class="font-bold">${esc(p.name)}</div><div class="text-xs text-slate-500 mt-1">${esc(p.code)} ${p.barcode?'· '+esc(p.barcode):''}</div><div class="flex justify-between mt-3"><span class="text-xs ${Number(p.stock)<=Number(p.min_stock)?'text-rose-600':'text-slate-500'}">Stok: ${p.stock}</span><b class="text-blue-600">${money(p.sale_price)}</b></div></button>`).join('')||'<p class="text-slate-400 col-span-full text-center py-10">Məhsul tapılmadı.</p>';
  box.querySelectorAll('.productBtn').forEach(b=>b.onclick=()=>addCart(b.dataset.id));
}
function addCart(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(i=>i.product_id===id);if(x){if(x.qty+1>Number(p.stock))return toast("Stok kifayət deyil",false);x.qty++}else{if(Number(p.stock)<1)return toast("Stok bitib",false);cart.push({product_id:id,name:p.name,price:Number(p.sale_price),qty:1,cost:Number(p.purchase_price||0)})}renderCart()}
function renderCart(){const box=document.getElementById('cart');if(!cart.length){box.innerHTML='<p class="text-center text-slate-400 py-12">Səbət boşdur</p>'}else box.innerHTML=cart.map((x,i)=>`<div class="border rounded-xl p-3"><div class="flex justify-between gap-2"><b class="text-sm">${esc(x.name)}</b><button onclick="removeCart(${i})" class="text-rose-500">✕</button></div><div class="flex items-center justify-between mt-2"><input onchange="cart[${i}].price=Number(this.value);renderCart()" value="${x.price}" type="number" step=".01" class="w-24 border rounded-lg px-2 py-1 text-sm"><div class="flex items-center gap-2"><button onclick="qtyCart(${i},-1)" class="w-7 h-7 border rounded-lg">−</button><b>${x.qty}</b><button onclick="qtyCart(${i},1)" class="w-7 h-7 border rounded-lg">+</button></div></div></div>`).join('');const sub=cart.reduce((a,x)=>a+x.qty*x.price,0),disc=Math.max(0,Number(document.getElementById('discount').value||0)),total=Math.max(0,sub-disc);document.getElementById('subtotal').textContent=money(sub);document.getElementById('total').textContent=money(total)}
function qtyCart(i,d){const x=cart[i],p=products.find(p=>p.id===x.product_id);if(d>0&&x.qty+d>Number(p.stock))return toast("Stok kifayət deyil",false);x.qty+=d;if(x.qty<=0)cart.splice(i,1);renderCart()}
function removeCart(i){cart.splice(i,1);renderCart()}
async function checkout(){if(!cart.length)return toast("Səbət boşdur",false);try{const d=await api("create_sale",{customer_id:document.getElementById('customerSelect').value||null,payment_type:document.getElementById('payment').value,discount:Number(document.getElementById('discount').value||0),items:cart.map(x=>({product_id:x.product_id,qty:x.qty,unit_price:x.price}))});toast(`Satış tamamlandı · ${d.invoice_no} · ${money(d.total)}`);cart=[];document.getElementById('discount').value=0;await loadAll();renderCart();nav('dashboard')}catch(e){toast(e.message,false)}}
function renderProductsTable(){const q=(document.getElementById('productsFilter')?.value||'').toLowerCase();document.getElementById('productsTable').innerHTML=products.filter(p=>`${p.code} ${p.name} ${p.barcode||''}`.toLowerCase().includes(q)).map(p=>`<tr class="border-b"><td class="p-3 font-mono">${esc(p.code)}</td><td class="p-3 font-semibold">${esc(p.name)}</td><td class="p-3 text-center ${Number(p.stock)<=Number(p.min_stock)?'text-rose-600 font-bold':''}">${p.stock}</td><td class="p-3 text-right">${money(p.purchase_price)}</td><td class="p-3 text-right font-bold">${money(p.sale_price)}</td><td class="p-3 text-center">${p.min_stock}</td></tr>`).join('')}
function renderCustomersTable(){const q=(document.getElementById('customersFilter')?.value||'').toLowerCase();document.getElementById('customersTable').innerHTML=customers.filter(c=>`${c.code} ${c.name} ${c.phone||''}`.toLowerCase().includes(q)).map(c=>`<tr class="border-b"><td class="p-3 font-mono">${esc(c.code)}</td><td class="p-3 font-semibold">${esc(c.name)}</td><td class="p-3 text-center">${esc(c.phone||'')}</td><td class="p-3 text-right ${Number(c.balance)>0?'text-rose-600 font-bold':''}">${money(c.balance)}</td><td class="p-3 text-right">${money(c.total_purchase)}</td></tr>`).join('')}
function renderStockSelect(){const s=document.getElementById('stockProduct');s.innerHTML=products.map(p=>`<option value="${p.id}">${esc(p.code)} · ${esc(p.name)} · stok ${p.stock}</option>`).join('')}
async function saveStock(){const product_id=document.getElementById('stockProduct').value,qty=Number(document.getElementById('stockQty').value),cost=Number(document.getElementById('stockCost').value);if(!product_id||qty<=0||cost<0)return toast("Məlumatları düzgün doldurun",false);try{await api("stock_in",{product_id,qty,cost});toast("Mədaxil yadda saxlanıldı");await loadAll()}catch(e){toast(e.message,false)}}
async function loadDashboard(){try{const d=await api("dashboard");document.getElementById('kSales').textContent=money(d.sales);document.getElementById('kProfit').textContent=money(d.profit);document.getElementById('kReturn').textContent=money(d.returns);document.getElementById('kExpense').textContent=money(d.expenses);document.getElementById('kLow').textContent=d.low_stock;document.getElementById('serverDate').textContent=`Server vaxtı: ${d.server_time}`;document.getElementById('recentSales').innerHTML=d.recent.map(x=>`<tr class="border-b"><td class="p-3 font-mono">${x.invoice_no}</td><td class="p-3">${x.created_at}</td><td class="p-3">${esc(x.customer_name||'Nağd Müştəri')}</td><td class="p-3 text-right font-bold">${money(x.total)}</td></tr>`).join('')||'<tr><td colspan="4" class="p-5 text-center text-slate-400">Satış yoxdur</td></tr>'}catch(e){toast(e.message,false)}}
async function loadSales(){try{const d=await api("sales");document.getElementById('salesTable').innerHTML=d.sales.map(x=>`<tr class="border-b"><td class="p-3 font-mono">${x.invoice_no}</td><td class="p-3">${x.created_at}</td><td class="p-3">${esc(x.user_name)}</td><td class="p-3">${esc(x.customer_name||'Nağd Müştəri')}</td><td class="p-3 text-right font-bold">${money(x.total)}</td><td class="p-3 text-center">${esc(x.payment_type)}</td></tr>`).join('')||'<tr><td colspan="6" class="p-5 text-center text-slate-400">Satış yoxdur</td></tr>'}catch(e){toast(e.message,false)}}
function modal(title,body,onSave){document.getElementById('modalTitle').textContent=title;document.getElementById('modalBody').innerHTML=body;document.getElementById('modal').classList.remove('hidden');document.getElementById('modal').classList.add('flex');document.getElementById('modalSave')?.addEventListener('click',onSave)}
async function createProduct(){modal("Yeni məhsul",`<div class="space-y-3"><input id="mCode" class="w-full border rounded-xl px-3 py-3" placeholder="Kod"><input id="mName" class="w-full border rounded-xl px-3 py-3" placeholder="Məhsul adı"><input id="mBarcode" class="w-full border rounded-xl px-3 py-3" placeholder="Barkod"><div class="grid grid-cols-2 gap-3"><input id="mCost" type="number" step=".01" class="border rounded-xl px-3 py-3" placeholder="Maya"><input id="mPrice" type="number" step=".01" class="border rounded-xl px-3 py-3" placeholder="Satış"></div><input id="mMin" type="number" min="0" class="w-full border rounded-xl px-3 py-3" placeholder="Minimum stok"></div><button id="modalSave" class="mt-5 w-full bg-blue-600 text-white py-3 rounded-xl font-bold">Yadda saxla</button>`,async()=>{try{await api("create_product",{code:mCode.value,name:mName.value,barcode:mBarcode.value||null,purchase_price:Number(mCost.value||0),sale_price:Number(mPrice.value||0),min_stock:Number(mMin.value||0)});closeModal();toast("Məhsul yaradıldı");await loadAll()}catch(e){toast(e.message,false)}})}
async function createCustomer(){modal("Yeni müştəri",`<div class="space-y-3"><input id="cCode" class="w-full border rounded-xl px-3 py-3" placeholder="Kod"><input id="cName" class="w-full border rounded-xl px-3 py-3" placeholder="Ad / şirkət"><input id="cPhone" class="w-full border rounded-xl px-3 py-3" placeholder="Telefon"><input id="cAddress" class="w-full border rounded-xl px-3 py-3" placeholder="Ünvan"></div><button id="modalSave" class="mt-5 w-full bg-blue-600 text-white py-3 rounded-xl font-bold">Yadda saxla</button>`,async()=>{try{await api("create_customer",{code:cCode.value,name:cName.value,phone:cPhone.value,address:cAddress.value});closeModal();toast("Müştəri yaradıldı");await loadAll()}catch(e){toast(e.message,false)}})}
function closeModal(){document.getElementById('modal').classList.add('hidden');document.getElementById('modal').classList.remove('flex')}
document.addEventListener('DOMContentLoaded',async()=>{if(!configured())showLoginError("config.js faylını doldurun.");document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>nav(b.dataset.view));document.getElementById('loginBtn').onclick=login;document.getElementById('logout').onclick=logout;document.getElementById('pin').onkeydown=e=>{if(e.key==='Enter')login()};document.getElementById('productSearch').oninput=renderProductResults;document.getElementById('discount').oninput=renderCart;document.getElementById('checkout').onclick=checkout;document.getElementById('clearCart').onclick=()=>{cart=[];renderCart()};document.getElementById('productsFilter').oninput=renderProductsTable;document.getElementById('customersFilter').oninput=renderCustomersTable;document.getElementById('newProduct').onclick=createProduct;document.getElementById('newCustomer').onclick=createCustomer;document.getElementById('saveStock').onclick=saveStock;document.getElementById('stockIn').onclick=()=>nav('stock');document.getElementById('refreshDash').onclick=loadDashboard;document.getElementById('modalClose').onclick=closeModal;
  try{const saved=JSON.parse(localStorage.getItem("decor_session")||"null");if(saved?.token&&saved?.user){session=saved;await startApp()}}catch(e){localStorage.removeItem("decor_session")}
});
document.addEventListener('keydown',e=>{if(document.getElementById('login').classList.contains('hidden') && document.activeElement?.id==='productSearch'){const bs=[...document.querySelectorAll('.productBtn')];if(e.key==='Enter'&&bs[0]){e.preventDefault();bs[0].click()}}});
