import { createClient } from "https://esm.sh/@supabase/supabase-js@2";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const json=(x:any,status=200)=>new Response(JSON.stringify(x),{status,headers:{...cors,"Content-Type":"application/json"}});
const cryptoHex=async(s:string)=>{const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(s));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")};
const db=createClient(Deno.env.get("SUPABASE_URL")!,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!);
async function auth(token:string){if(!token)throw Error("Sessiya yoxdur");const h=await cryptoHex(token);const {data,error}=await db.from("user_sessions").select("id,user_id,expires_at,users(id,name,role,active)").eq("token_hash",h).maybeSingle();if(error||!data||new Date(data.expires_at)<=new Date()||(data.users as any)?.active!==true)throw Error("Sessiya etibarsızdır");return data.users as any}
function token(){const a=new Uint8Array(32);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,"0")).join("")}
Deno.serve(async(req)=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const body=await req.json();const action=body.action;
if(action==="login"){const pin=String(body.pin||"").trim();if(!pin)throw Error("Giriş kodu daxil edin");const {data,error}=await db.from("users").select("id,name,role,pin_hash,active").eq("active",true);if(error)throw error;let found:any=null;for(const x of data||[]){const {data:ok,error:e}=await db.rpc("verify_pin",{p_hash:x.pin_hash,p_pin:pin});if(!e&&ok===true){found=x;break}}if(!found)throw Error("Giriş kodu səhvdir");const raw=token(),hash=await cryptoHex(raw);await db.from("user_sessions").insert({user_id:found.id,token_hash:hash,login_at:new Date().toISOString(),expires_at:new Date(Date.now()+12*3600*1000).toISOString()});return json({token:raw,user:{id:found.id,name:found.name,role:found.role}})}
const user=await auth(body.session_token);
if(action==="logout"){const h=await cryptoHex(body.session_token);await db.from("user_sessions").update({logout_at:new Date().toISOString()}).eq("token_hash",h);return json({ok:true})}
if(action==="bootstrap"){const productQuery=user.role==="admin"?db.from("products").select("id,code,barcode,name,category,unit,purchase_price,sale_price,stock,min_stock,active").order("name"):db.from("products").select("id,code,barcode,name,category,unit,purchase_price,sale_price,stock,min_stock,active").eq("active",true).order("name");const [p,c,w,ws,t,cl]=await Promise.all([productQuery,db.from("customers").select("id,code,name,phone,address,balance,total_purchase").order("name"),db.from("warehouses").select("id,code,name,address").eq("active",true).order("name"),db.from("warehouse_stock").select("warehouse_id,product_id,stock"),db.rpc("server_time_baku"),db.from("day_closings").select("business_date,closed_at,closed_by,users(name)").eq("business_date",new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Baku"})).maybeSingle()]);if(p.error)throw p.error;if(c.error)throw c.error;if(w.error)throw w.error;if(ws.error)throw ws.error;return json({products:p.data||[],customers:c.data||[],warehouses:w.data||[],warehouse_stock:ws.data||[],server_time:t.data,day_closed:!!cl.data,day_closing:cl.data||null})}
if(action==="create_product"){if(user.role!=="admin")throw Error("Yalnız admin məhsul yarada bilər");const x=body;if(!x.name)throw Error("Məhsul adı tələb olunur");const {data,error}=await db.rpc("create_product_auto",{p_user_id:user.id,p_name:x.name.trim(),p_barcode:x.barcode||null,p_category:x.category||null,p_purchase_price:Number(x.purchase_price||0),p_sale_price:Number(x.sale_price||0),p_min_stock:Number(x.min_stock||0)});if(error)throw error;return json({product:data})}
if(action==="admin_update_product"){if(user.role!=="admin")throw Error("Yalnız admin məhsul dəyişə bilər");const x=body;const {data,error}=await db.rpc("admin_update_product",{p_admin_id:user.id,p_product_id:x.product_id,p_name:x.name,p_barcode:x.barcode||null,p_category:x.category||null,p_unit:x.unit||"ədəd",p_purchase_price:Number(x.purchase_price||0),p_sale_price:Number(x.sale_price||0),p_min_stock:Number(x.min_stock||0),p_active:x.active!==false,p_warehouse_id:x.warehouse_id||null,p_warehouse_stock:x.warehouse_stock===null||x.warehouse_stock===undefined?null:Number(x.warehouse_stock)});if(error)throw error;return json(data)}
if(action==="create_customer"){const x=body;if(!x.name)throw Error("Ad / şirkət tələb olunur");const {data,error}=await db.rpc("create_customer_auto",{p_user_id:user.id,p_name:x.name.trim(),p_phone:x.phone||null,p_address:x.address||null});if(error)throw error;return json({customer:data})}
if(action==="admin_data"){if(user.role!=="admin")throw Error("Yalnız admin");const [us,ss,rr,mm,ee,ww,cc]=await Promise.all([db.from("users").select("id,name,role,phone,active,created_at,updated_at").order("name"),db.from("sales").select("id,invoice_no,created_at,total,payment_type,user_id,users!sales_user_id_fkey(name),customers(name),warehouses(name)").order("created_at",{ascending:false}).limit(1000),db.from("returns").select("id,sale_id,product_id,user_id,warehouse_id,qty,amount,reason,created_at,users(name),products(name),warehouses(name)").order("created_at",{ascending:false}).limit(1000),db.from("stock_movements").select("id,product_id,user_id,warehouse_id,movement_type,qty,unit_cost,reference_id,created_at,users(name),products(name),warehouses(name)").order("created_at",{ascending:false}).limit(2000),db.from("expenses").select("id,user_id,description,amount,payment_type,created_at,users(name)").order("created_at",{ascending:false}).limit(1000),db.from("warehouses").select("id,code,name,address,active,created_at").order("name"),db.from("day_closings").select("business_date,closed_at,closed_by,users(name)").order("business_date",{ascending:false}).limit(60)]);for(const q of [us,ss,rr,mm,ee,ww,cc])if(q.error)throw q.error;const lg=await db.from("user_sessions").select("id,user_id,login_at,logout_at,expires_at,users(name,role)").order("login_at",{ascending:false}).limit(1000);if(lg.error)throw lg.error;return json({users:us.data||[],sales:ss.data||[],returns:rr.data||[],movements:mm.data||[],expenses:ee.data||[],warehouses:ww.data||[],closings:cc.data||[],sessions:lg.data||[]})}
if(action==="create_warehouse"){if(user.role!=="admin")throw Error("Yalnız admin anbar yarada bilər");const {data,error}=await db.from("warehouses").insert({code:body.code.trim(),name:body.name.trim(),address:body.address||null}).select().single();if(error)throw error;return json({warehouse:data})}
if(action==="create_expense"){const {data,error}=await db.rpc("create_expense",{p_user_id:user.id,p_description:body.description,p_amount:Number(body.amount),p_payment_type:body.payment_type});if(error)throw error;return json(data)}
if(action==="admin_upsert_user"){if(user.role!=="admin")throw Error("Yalnız admin");const {data,error}=await db.rpc("admin_upsert_user",{p_admin_id:user.id,p_user_id:body.user_id||null,p_name:body.name,p_role:body.role,p_pin:body.pin||null,p_phone:body.phone||null,p_active:body.active!==false});if(error)throw error;return json(data)}
if(action==="admin_delete_user"){if(user.role!=="admin")throw Error("Yalnız admin");const {data,error}=await db.rpc("admin_delete_user",{p_admin_id:user.id,p_user_id:body.user_id});if(error)throw error;return json({ok:data})}
if(action==="close_day"){if(user.role!=="admin")throw Error("Yalnız admin gün sonunu bağlaya bilər");const {data,error}=await db.rpc("close_business_day",{p_user_id:user.id,p_note:body.note||null});if(error)throw error;return json(data)}
if(action==="reopen_day"){if(user.role!=="admin")throw Error("Yalnız admin günü aça bilər");const {data,error}=await db.rpc("reopen_business_day",{p_user_id:user.id,p_date:body.date||new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Baku"})});if(error)throw error;return json({ok:data})}
if(action==="stock_in"){if(user.role!=="admin"){const dc=await db.from("day_closings").select("id").eq("business_date",new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Baku"})).maybeSingle();if(dc.data)throw Error("Bu gün bağlanıb. Yalnız admin əməliyyat edə bilər");}const {error}=await db.rpc("stock_in_atomic",{p_user_id:user.id,p_product_id:body.product_id,p_qty:Number(body.qty),p_cost:Number(body.cost),p_warehouse_id:body.warehouse_id});if(error)throw error;return json({ok:true})}
if(action==="create_sale"){if(user.role!=="admin"){const dc=await db.from("day_closings").select("id").eq("business_date",new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Baku"})).maybeSingle();if(dc.data)throw Error("Bu gün bağlanıb. Yalnız admin əməliyyat edə bilər");}const {data,error}=await db.rpc("create_sale_atomic",{p_user_id:user.id,p_customer_id:body.customer_id||null,p_payment_type:body.payment_type,p_discount:Number(body.discount||0),p_items:body.items,p_warehouse_id:body.warehouse_id});if(error)throw error;return json(data)}
if(action==="dashboard"){const {data,error}=await db.rpc("dashboard_today");if(error)throw error;return json(data)}
if(action==="sales"){const {data,error}=await db.from("sales").select("id,invoice_no,created_at,total,payment_type,users!sales_user_id_fkey(name),customers(name)").order("created_at",{ascending:false}).limit(500);if(error)throw error;return json({sales:(data||[]).map((x:any)=>({id:x.id,invoice_no:x.invoice_no,created_at:new Date(x.created_at).toLocaleString("az-AZ",{timeZone:"Asia/Baku"}),total:x.total,payment_type:x.payment_type,user_name:x.users?.name||"",customer_name:x.customers?.name||""}))})}
if(action==="sale_detail"||action==="sale_by_invoice"){let saleQuery=db.from("sales").select("id,invoice_no,created_at,subtotal,discount,total,payment_type,customer_id,warehouse_id,users!sales_user_id_fkey(name),customers(name),warehouses(name)");saleQuery=action==="sale_detail"?saleQuery.eq("id",body.sale_id).single():saleQuery.eq("invoice_no",body.invoice_no).single();const {data:sale,error}=await saleQuery;if(error||!sale)throw Error("Qaimə tapılmadı");const {data:items,error:ie}=await db.from("sale_items").select("product_id,qty,unit_price,purchase_cost,products(name)").eq("sale_id",sale.id);if(ie)throw ie;const ids=(items||[]).map((x:any)=>x.product_id);const {data:rets}=await db.from("returns").select("product_id,qty").eq("sale_id",sale.id);const returned:any={};for(const r of rets||[])returned[r.product_id]=(returned[r.product_id]||0)+Number(r.qty);return json({sale:{id:sale.id,invoice_no:sale.invoice_no,created_at:new Date(sale.created_at).toLocaleString("az-AZ",{timeZone:"Asia/Baku"}),subtotal:sale.subtotal,discount:sale.discount,total:sale.total,payment_type:sale.payment_type,customer_id:sale.customer_id,customer_name:(sale.customers as any)?.name||"",warehouse_id:sale.warehouse_id,warehouse_name:(sale.warehouses as any)?.name||"",user_name:(sale.users as any)?.name||""},items:(items||[]).map((x:any)=>({product_id:x.product_id,product_name:x.products?.name||"",qty:x.qty,unit_price:x.unit_price,purchase_cost:x.purchase_cost,returned_qty:returned[x.product_id]||0}))})}
if(action==="return_sale"){if(user.role!=="admin"){const dc=await db.from("day_closings").select("id").eq("business_date",new Date().toLocaleDateString("en-CA",{timeZone:"Asia/Baku"})).maybeSingle();if(dc.data)throw Error("Bu gün bağlanıb. Yalnız admin əməliyyat edə bilər");}const {data,error}=await db.rpc("return_sale_item",{p_user_id:user.id,p_sale_id:body.sale_id,p_product_id:body.product_id,p_qty:Number(body.qty),p_reason:body.reason||null,p_warehouse_id:body.warehouse_id});if(error)throw error;return json(data)}
if(action==="admin_delete_sale"){if(user.role!=="admin")throw Error("Yalnız admin qaimə silə bilər");const {data,error}=await db.rpc("admin_delete_sale",{p_user_id:user.id,p_sale_id:body.sale_id});if(error)throw error;return json(data)}
if(action==="admin_edit_sale"){if(user.role!=="admin")throw Error("Yalnız admin qaiməni dəyişə bilər");const {data,error}=await db.rpc("admin_edit_sale",{p_user_id:user.id,p_sale_id:body.sale_id,p_customer_id:body.customer_id||null,p_payment_type:body.payment_type,p_discount:Number(body.discount||0),p_items:body.items,p_warehouse_id:body.warehouse_id});if(error)throw error;return json(data)}
throw Error("Naməlum əməliyyat");}catch(e:any){return json({error:e.message||String(e)},400)}});
